# Generated by Django 5.2.6 on 2025-09-15 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('PAS', 'Pasaporte'), ('NIT', 'NIT')], default='CI', max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('puntuacion_crediticia', models.IntegerField(default=0)),
                ('es_cliente_preferencial', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(default='157F163DB6', max_length=10, unique=True)),
                ('departamento', models.CharField(choices=[('CREDITO', 'Crédito'), ('ADMIN', 'Administración'), ('TESORERIA', 'Tesorería'), ('ATENCION', 'Atención al Cliente')], max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_supervisor', models.BooleanField(default=False)),
                ('puede_aprobar_creditos', models.BooleanField(default=False)),
                ('limite_aprobacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
    ]
