# Generated by Django 5.2.6 on 2025-10-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(default='ED30433773', max_length=10, unique=True),
        ),
    ]
