# Generated by Django 5.2.6 on 2025-10-07 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_empleado_codigo_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(default='F24F228DAD', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('tasa_nominal_anual', models.DecimalField(decimal_places=4, max_digits=7)),
                ('moneda', models.CharField(default='BOB', max_length=10)),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('ENVIADA', 'Enviada'), ('EVALUADA', 'Evaluada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='ENVIADA', max_length=10)),
                ('score_riesgo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion_evaluacion', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='api.cliente')),
                ('oficial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='api.empleado')),
            ],
            options={
                'db_table': 'solicitudes_credito',
                'ordering': ['-created_at'],
            },
        ),
    ]
