# Generated by Django 5.2.6 on 2025-10-07 02:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_solicitud_credito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(default='01A862C23B', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metodo', models.CharField(default='frances', max_length=20)),
                ('moneda', models.CharField(default='BOB', max_length=10)),
                ('primera_cuota_fecha', models.DateField()),
                ('total_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_interes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_cuotas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('redondeo_ajuste_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='api.solicitudcredito')),
            ],
            options={
                'db_table': 'plan_pago',
            },
        ),
        migrations.CreateModel(
            name='PlanCuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_cuenta', models.IntegerField(default=0)),
                ('nro_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ajuste_redondeo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='api.planpago')),
            ],
            options={
                'db_table': 'plan_cuota',
                'ordering': ['nro_cuota'],
                'unique_together': {('plan', 'nro_cuota')},
            },
        ),
    ]
