# Generated by Django 5.2.6 on 2025-10-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_plan_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('vigencia_dias', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento_tipo',
            },
        ),
        migrations.CreateModel(
            name='ProductoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PERSONAL', 'Personal/Consumo'), ('VEHICULAR', 'Vehicular'), ('HIPOTECARIO', 'Hipotecario'), ('PYME', 'Micro/Pequeña Empresa')], max_length=20)),
                ('tasa_nominal_anual_min', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tasa_nominal_anual_max', models.DecimalField(decimal_places=4, max_digits=7)),
                ('plazo_min', models.PositiveIntegerField()),
                ('plazo_max', models.PositiveIntegerField()),
                ('monto_min', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_max', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo_amortizacion_default', models.CharField(default='frances', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto_financiero',
            },
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tipo_credito',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('VEHICULAR', 'Vehicular'), ('HIPOTECARIO', 'Hipotecario'), ('PYME', 'Micro/Pequeña Empresa')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='tipo_trabajador',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('INDEPENDIENTE', 'Independiente')], default='PRIVADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codigo_empleado',
            field=models.CharField(default='B21048811B', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes/%Y/%m/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('valido', models.BooleanField(default=None, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='api.solicitudcredito')),
                ('documento_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.documentotipo')),
            ],
            options={
                'db_table': 'documento_adjunto',
            },
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.productofinanciero'),
        ),
        migrations.CreateModel(
            name='RequisitoProductoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajador', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('INDEPENDIENTE', 'Independiente')], max_length=20)),
                ('obligatorio', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.documentotipo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='api.productofinanciero')),
            ],
            options={
                'db_table': 'req_prod_doc',
                'unique_together': {('producto', 'tipo_trabajador', 'documento')},
            },
        ),
    ]
