name: entidad_financiera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'   # rango seguro; ajusta si tu Flutter pide otro

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.1.3        # Usa una sola versión. Si prefieres 16.x, usa esa SOLO aquí
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.2
  state_notifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
